# -*- coding: utf-8 -*-
"""오일러 프로젝트_이다은.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y2jNHTznR2gAKQwpO9t4NWpiJLM6q8KO

# **[ 오일러 프로젝트 ]**
### - KQR 7기 이다은
"""

# Problem 1
s = 0
for i in range(1000):
    if i%3==0 or i%5==0:
        s = s + i
    else:
        pass
    
print(s)

"""for문으로 시도하면 매우 오래걸리니 그냥 더할것!"""

# Problem 2
n1 = 0
n2 = 1
n3 = n1+n2
result = 0

while n3<=4000000:
  n3 = n1+n2
  # print(n3)
  n1 = n2
  n2 = n3

  if n3 % 2==0:
    result += n3

print('result_sum : ', result)

# Problem 3
a = 600851475143 
i = 2 
num = []
while (i<=a):
    if a%i==0:  
        num.append(i)
        a = a//i   # 이게 열쇠이다!
    i = i+1
print(max(num))

# Problem 4
a = "9009"
a[0] + a[1] == a[3] + a[2]







































